openapi: '3.0.2'
info:
  title: My Thai Star REST API
  description: |-
    This API file is just an example to show the options when creting an OpenAPI file.
    This Api is a small example for the My Thai Star
  version: '1.0'
  contact:
    email: contact@mail.de
paths:
  /booking:
    post:
      tags:
        - "Booking"
      summary: Create a new Booking
      description: Creates and retruns a new Booking
      operationId: createBooking
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'

    get:
      tags:
        - "Booking"
      summary: Get all Bookings
      description: Returns a list of bookings
      operationId: getBookingAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'


  /booking/{bookingId}:
    get:
      tags:
        - "Booking"
      summary: Find a single booking by Id
      description: Returns a single booking
      operationId: getBookingById
      parameters:
        - name: bookingId
          in: path
          description: ID of booking to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'

        '400':
          description: Invalid ID supplied
        '404':
          description: Booking not found

  /invitedGuest:
    post:
      tags:
        - "InvitedGuest"
      summary: Create a new invited guests
      description: Creates and retruns a new invited guests
      operationId: createInvitedGuest
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitedGuest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvitedGuest'

    get:
      tags:
        - "InvitedGuest"
      summary: Get all invited guests
      description: Returns a list of invited guests
      operationId: getInvitedGuestAll
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InvitedGuest'

  /invitedGuest/{guestId}:
    get:
      tags:
        - "InvitedGuest"
      summary: Find a single InvitedGuest by Id
      description: Returns a single InvitedGuest
      operationId: getInvitedGuestById
      parameters:
        - name: guestId
          in: path
          description: ID of guest to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvitedGuest'

        '400':
          description: Invalid ID supplied
        '404':
          description: InvitedGuest not found

components:
  schemas:

    InvitedGuest:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        modificationCounter:
          type: integer
          format: int32
          default: 0
          example: 0
        email:
          type: string
          example: "guest.email@email.com"

    Booking:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        modificationCounter:
          type: integer
          format: int32
          default: 0
          example: 0
        invitedGuests:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/InvitedGuest'
          example: []
          default: []