global:
  scrape_interval: 10s
  external_labels:
    monitor: 'tracing-example'

scrape_configs:
  - job_name: 'tracing-example'
    scrape_interval: 10s
    static_configs:
      - targets: [localhost:8080]


  - job_name: loki
    scrape_interval: 10s
    static_configs:
      - targets: [loki:3100]

  - job_name: tempo
    scrape_interval: 10s
    static_configs:
      - targets: [tempo:3200]