{
 "title": "Tracing Example",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Tracing Example", "type": "text", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` |= \"/observability\" [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` |= \"/service1\" [$__interval]))",
     "legendFormat": "{{path}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(job) (count_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [$__interval]))",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Requests by status code",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (path) (sum_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` |= \"/service1\" | unwrap size [1m]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by (path) (sum_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` |= \"/customers\" | unwrap size [1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "HTTP status codes over time, per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time( {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Service Up/Down",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "up{job=\"tracing-example\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate (requests_total[1m])) * 60",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate(request_duration_histogram_bucket{}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "90% Percentile Response Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "quantile_over_time (0.90, {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" | unwrap size [1m] ) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (path) (rate(requests_total{job=\"tracing-example\"} [1m]) * 60)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum by (path) (rate( {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" | status !=200 [1m])) / sum by (path) (rate( {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [1m])) * 100",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(request_duration_histogram_bucket{}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"tracing-example\"}"
    }
   ]
  }
 ]
}