version: "3"
services:

  # The tracing-example application
  tracing-example-jvm:
    image: quarkus/tracing-example-jvm
    volumes:
      - ./logs/tracing.log:/tmp/tracing.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://agent:4317
      OTEL_SERVICE_NAME: tracing-example
      OTEL_TRACES_EXPORTER: otlp
    ports:
      - "8080:8080"

  # Our load generator
  load-generator:
    image: curlimages/curl:latest
    volumes:
      - ../tracing-example/load-generator.sh:/tmp/load-generator.sh
    command: /bin/sh -c "/tmp/load-generator.sh"
  
  agent:
    image: grafana/agent:v0.25.1
    volumes:
      - ./config/agent.yaml:/etc/agent-config/agent.yaml
      - ./logs/tracing.log:/tmp/tracing.log
      - ./logs/access_log.log:/tmp/access_log.log
      # - /:/host/root:ro,rslave
      # - /sys:/host/sys:ro,rslave
      # - /proc:/host/proc:ro,rslave
      - /tmp/agent:/etc/agent
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
    ports:
      - "4317:4317"
